/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.28.                           *
*        Compiled Jan 30 2015, 16:40:04                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: CLOSE                                                 *
* Dimensions:  32 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmCLOSE;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsCLOSE[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalCLOSE = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsCLOSE[0]
};

static GUI_CONST_STORAGE unsigned char _acCLOSE[] = {
  ________, ________, ________, ________,
  __X_____, ________, ________, _____X__,
  _XXX____, ________, ________, ____XXX_,
  __XXX___, ________, ________, ___XXX__,
  ___XXX__, ________, ________, __XXX___,
  ____XXX_, ________, ________, _XXX____,
  _____XXX, ________, ________, XXX_____,
  ______XX, X_______, _______X, XX______,
  _______X, XX______, ______XX, X_______,
  ________, XXX_____, _____XXX, ________,
  ________, _XXX____, ____XXX_, ________,
  ________, __XXX___, ___XXX__, ________,
  ________, ___XXX__, __XXX___, ________,
  ________, ____XXX_, _XXX____, ________,
  ________, _____XXX, XXX_____, ________,
  ________, ______XX, XX______, ________,
  ________, ______XX, XX______, ________,
  ________, _____XXX, XXX_____, ________,
  ________, ____XXX_, _XXX____, ________,
  ________, ___XXX__, __XXX___, ________,
  ________, __XXX___, ___XXX__, ________,
  ________, _XXX____, ____XXX_, ________,
  ________, XXX_____, _____XXX, ________,
  _______X, XX______, ______XX, X_______,
  ______XX, X_______, _______X, XX______,
  _____XXX, ________, ________, XXX_____,
  ____XXX_, ________, ________, _XXX____,
  ___XXX__, ________, ________, __XXX___,
  __XXX___, ________, ________, ___XXX__,
  _XXX____, ________, ________, ____XXX_,
  __X_____, ________, ________, _____X__,
  ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmCLOSE = {
  32, // xSize
  32, // ySize
  4, // BytesPerLine
  1, // BitsPerPixel
  _acCLOSE,  // Pointer to picture data (indices)
  &_PalCLOSE   // Pointer to palette
};

/*************************** End of file ****************************/
