/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.24.                           *
*        Compiled Jan 27 2014, 11:27:47                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: NO                                                    *
* Dimensions:  26 * 26                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmNO;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsNO[] = {
  0xFFFFFF, GUI_RED//0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalNO = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsNO[0]
};

static GUI_CONST_STORAGE unsigned char _acNO[] = {
  _XX_____, ________, _______X, X_______,
  XXXX____, ________, ______XX, XX______,
  XXXXX___, ________, _____XXX, XX______,
  _XXXXX__, ________, ____XXXX, X_______,
  __XXXXX_, ________, ___XXXXX, ________,
  ___XXXXX, ________, __XXXXX_, ________,
  ____XXXX, X_______, _XXXXX__, ________,
  _____XXX, XX______, XXXXX___, ________,
  ______XX, XXX____X, XXXX____, ________,
  _______X, XXXX__XX, XXX_____, ________,
  ________, XXXXXXXX, XX______, ________,
  ________, _XXXXXXX, X_______, ________,
  ________, __XXXXXX, ________, ________,
  ________, __XXXXXX, ________, ________,
  ________, _XXXXXXX, X_______, ________,
  ________, XXXXXXXX, XX______, ________,
  _______X, XXXX__XX, XXX_____, ________,
  ______XX, XXX____X, XXXX____, ________,
  _____XXX, XX______, XXXXX___, ________,
  ____XXXX, X_______, _XXXXX__, ________,
  ___XXXXX, ________, __XXXXX_, ________,
  __XXXXX_, ________, ___XXXXX, ________,
  _XXXXX__, ________, ____XXXX, X_______,
  XXXXX___, ________, _____XXX, XX______,
  XXXX____, ________, ______XX, XX______,
  _XX_____, ________, _______X, X_______
};

GUI_CONST_STORAGE GUI_BITMAP bmNO = {
  26, // xSize
  26, // ySize
  4, // BytesPerLine
  1, // BitsPerPixel
  _acNO,  // Pointer to picture data (indices)
  &_PalNO   // Pointer to palette
};

/*************************** End of file ****************************/
