/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.24.                           *
*        Compiled Jan 27 2014, 11:27:47                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: OK                                                    *
* Dimensions:  38 * 26                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmOK;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/

static GUI_CONST_STORAGE GUI_COLOR _ColorsOK[] = {
  0xFFFFFF, 0x0000c000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalOK = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsOK[0]
};

static GUI_CONST_STORAGE unsigned char _acOK[] = {
  ________, ________, ________, ________, ___XX___,
  ________, ________, ________, ________, __XXXX__,
  ________, ________, ________, ________, _XXXXX__,
  ________, ________, ________, ________, XXXXX___,
  ________, ________, ________, _______X, XXXX____,
  ________, ________, ________, ______XX, XXX_____,
  ________, ________, ________, _____XXX, XX______,
  ________, ________, ________, ____XXXX, X_______,
  ________, ________, ________, ___XXXXX, ________,
  ________, ________, ________, __XXXXX_, ________,
  ________, ________, ________, _XXXXX__, ________,
  _XX_____, ________, ________, XXXXX___, ________,
  XXXX____, ________, _______X, XXXX____, ________,
  XXXXX___, ________, ______XX, XXX_____, ________,
  _XXXXX__, ________, _____XXX, XX______, ________,
  __XXXXX_, ________, ____XXXX, X_______, ________,
  ___XXXXX, ________, ___XXXXX, ________, ________,
  ____XXXX, X_______, __XXXXX_, ________, ________,
  _____XXX, XX______, _XXXXX__, ________, ________,
  ______XX, XXX_____, XXXXX___, ________, ________,
  _______X, XXXX___X, XXXX____, ________, ________,
  ________, XXXXX_XX, XXX_____, ________, ________,
  ________, _XXXXXXX, XX______, ________, ________,
  ________, __XXXXXX, X_______, ________, ________,
  ________, ___XXXXX, ________, ________, ________,
  ________, ____XXX_, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmOK = {
  38, // xSize
  26, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _acOK,  // Pointer to picture data (indices)
  &_PalOK   // Pointer to palette
};

/*************************** End of file ****************************/
