/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.24                          *
 *        Compiled Jan 27 2014, 11:28:24                              *
 *        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */
#include "SetArchiveDLG.h"
#include "parameters.h"
#include "draw.h"
#include "skins.h"
#include "UserMessage.h"
#include "buzzer.h"
#include "passwords.h"

extern GUI_CONST_STORAGE GUI_FONT GUI_FontLato30;

extern GUI_CONST_STORAGE GUI_BITMAP bmOK;
extern GUI_CONST_STORAGE GUI_BITMAP bmNO;

#define ID_WINDOW_SET_ARCHIVE     				(GUI_ID_USER + 0x200)
#define ID_BUTTON_OK    									(GUI_ID_USER + 0x201)
#define ID_TEXT_ARCHIVE_FREQUENCY     		(GUI_ID_USER + 0x202)
#define ID_TEXT_ARCHIVE_SIZE     					(GUI_ID_USER + 0x203)
#define ID_TEXT_TOT_ARCHIVE_FREQUENCY     (GUI_ID_USER + 0x204)
#define ID_DROPDOWN_ARCHIVE_FREQUENCY_1   (GUI_ID_USER + 0x205)
#define ID_DROPDOWN_ARCHIVE_FREQUENCY_2   (GUI_ID_USER + 0x206)
#define ID_DROPDOWN_TOT_ARCHIVE_FREQUENCY	(GUI_ID_USER + 0x207)
#define ID_MULTIPAGE_ARCHIVE_DATA    			(GUI_ID_USER + 0x208)
#define ID_BUTTON_CANCEL  								(GUI_ID_USER + 0x209)
#define ID_DROPDOWN_ARCHIVE_SIZE     			(GUI_ID_USER + 0x20A)
#define ID_TEXT_USER_START_STOP     			(GUI_ID_USER + 0x20B)
#define ID_CHECKBOX_USER_START_STOP     	(GUI_ID_USER + 0x20C)

static ARCHIVE_SETTINGS tempArchiveSettings __attribute__ ((section(".sdram")));

extern uint8_t NewSettings __attribute__ ((section(".sdram")));

const char ArchiveFrequencyDescription[15][7] =
		{
				"2 s",
				"5 s",
				"10 s",
				"15 s",
				"30 s",
				"1 min",
				"5 min",
				"10 min",
				"15 min",
				"30 min",
				"1 h",
				"2 h",
				"4 h",
				"12 h",
				"24 h"
		};

const char TotalizerArchiveFrequencyDescription[10][7] =
		{
				"1 min",
				"5 min",
				"10 min",
				"15 min",
				"30 min",
				"1 h",
				"2 h",
				"4 h",
				"12 h",
				"24 h"
		};

extern WM_HWIN CreateArchiveValuesWindow(WM_HWIN hParent);
extern WM_HWIN CreateArchiveTotalizersWindow(WM_HWIN hParent);

/**********************************************************************
 * Elementy tworzące okna
 **********************************************************************/
static const GUI_WIDGET_CREATE_INFO _aSetArchiveDialogCreate[] =
		{
				{ WINDOW_CreateIndirect, "", ID_WINDOW_SET_ARCHIVE, 0, 0, 740, 420, 0, 0x0, 0 },
				{ BUTTON_CreateIndirect, "", ID_BUTTON_OK, 496, 360, 120, 58, 0, 0x0, 0 },
				{ BUTTON_CreateIndirect, "", ID_BUTTON_CANCEL, 618, 360, 120, 58, 0, 0x0, 0 },
				{ TEXT_CreateIndirect, "", ID_TEXT_ARCHIVE_SIZE, 10, 10, 360, 40, 0, 0x0, 0 },
				{ TEXT_CreateIndirect, "", ID_TEXT_ARCHIVE_FREQUENCY, 10, 55, 360, 40, 0, 0x0, 0 },
				{ TEXT_CreateIndirect, "", ID_TEXT_TOT_ARCHIVE_FREQUENCY, 10, 100, 360, 40, 0, 0x0, 0 },
				{ DROPDOWN_CreateIndirect, "", ID_DROPDOWN_ARCHIVE_SIZE, 370, 10, 180, 90, 0, 0x0, 0 },
				{ DROPDOWN_CreateIndirect, "", ID_DROPDOWN_ARCHIVE_FREQUENCY_1, 370, 55, 180, 210, 0, 0x0, 0 },
				{ DROPDOWN_CreateIndirect, "", ID_DROPDOWN_ARCHIVE_FREQUENCY_2, 590, 55, 140, 210, 0, 0x0, 0 },
				{ DROPDOWN_CreateIndirect, "", ID_DROPDOWN_TOT_ARCHIVE_FREQUENCY, 370, 100, 180, 210, 0, 0x0, 0 },

				{ MULTIPAGE_CreateIndirect, "Multipage", ID_MULTIPAGE_ARCHIVE_DATA, 5, 145, 730, 210, 0, 0x0, 0 },

				{ TEXT_CreateIndirect, "", ID_TEXT_USER_START_STOP, 10, 370, 390, 35, 0, 0x0, 0 },
				{ CHECKBOX_CreateIndirect, "", ID_CHECKBOX_USER_START_STOP, 405, 370, 35, 35, 0, 0x0, 0 },


		};

/**********************************************************************
 * Funkcje odpowiedzalne za obsługę okien
 **********************************************************************/
static void _cbSetArchiveDialog(WM_MESSAGE * pMsg)
{
	WM_HWIN hItem;
	int NCode;
	int Id;
	int i;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		CopyArchiveSettings(&tempArchiveSettings, &bkArchiveSettings);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ARCHIVE_FREQUENCY);
		TEXT_SetTextColor(hItem, GUI_BLUE);
		TEXT_SetText(hItem, GUI_LANG_GetText(59));

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ARCHIVE_SIZE);
		TEXT_SetTextColor(hItem, GUI_BLUE);
		TEXT_SetText(hItem, GUI_LANG_GetText(159));

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TOT_ARCHIVE_FREQUENCY);
		TEXT_SetTextColor(hItem, GUI_BLUE);
		TEXT_SetText(hItem, GUI_LANG_GetText(60));

		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_ARCHIVE_FREQUENCY_1);
		DROPDOWN_SetTextSkin(hItem);
		DROPDOWN_SetAutoScroll(hItem, 1);
		for (i = 0; i < 15; i++)
			DROPDOWN_AddString(hItem, ArchiveFrequencyDescription[i]);
		DROPDOWN_SetSel(hItem, tempArchiveSettings.ArchivizationFrequency1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_ARCHIVE_FREQUENCY_2);
		DROPDOWN_SetTextSkin(hItem);
		DROPDOWN_SetAutoScroll(hItem, 1);
		for (i = 0; i < 15; i++)
			DROPDOWN_AddString(hItem, ArchiveFrequencyDescription[i]);
		DROPDOWN_SetSel(hItem, tempArchiveSettings.ArchivizationFrequency2);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_TOT_ARCHIVE_FREQUENCY);
		DROPDOWN_SetTextSkin(hItem);
		DROPDOWN_SetAutoScroll(hItem, 1);
		for (i = 0; i < 10; i++)
			DROPDOWN_AddString(hItem, TotalizerArchiveFrequencyDescription[i]);
		DROPDOWN_SetSel(hItem, tempArchiveSettings.TotalizerArchivizationFrequency);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_ARCHIVE_SIZE);
		DROPDOWN_SetTextSkin(hItem);
		DROPDOWN_SetAutoScroll(hItem, 1);
		DROPDOWN_AddString(hItem, GUI_LANG_GetText(43));
		DROPDOWN_AddString(hItem, GUI_LANG_GetText(44));
		DROPDOWN_AddString(hItem, GUI_LANG_GetText(45));
		DROPDOWN_SetSel(hItem, tempArchiveSettings.ArchiveMaxSize);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_ARCHIVE_DATA);
		MULTIPAGE_EnableScrollbar(hItem, 0);
		MULTIPAGE_AddPage(hItem, CreateArchiveValuesWindow(hItem), GUI_LANG_GetText(61));
		MULTIPAGE_AddPage(hItem, CreateArchiveTotalizersWindow(hItem), GUI_LANG_GetText(24));
		MULTIPAGE_SetTabWidth(hItem, 364, 0);
		MULTIPAGE_SetTabWidth(hItem, 364, 1);
		MULTIPAGE_SelectPage(hItem, 0);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
		BUTTON_SetBitmapEx(hItem, 0, &bmOK, 41, 16);
		if (PASSWORDS_GetCurrentLevel() < USER_LEVEL)
			WM_HideWindow(hItem);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
		BUTTON_SetBitmapEx(hItem, 0, &bmNO, 47, 16);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_USER_START_STOP);
		TEXT_SetTextColor(hItem, GUI_BLUE);
		TEXT_SetText(hItem, GUI_LANG_GetText(220));

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_USER_START_STOP);
		CHECKBOX_SetState(hItem, tempArchiveSettings.canUserStopArchive);

		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id)
		{
		case ID_BUTTON_OK:
			switch (NCode)
			{
			case WM_NOTIFICATION_RELEASED:
				BUZZER_Beep();

				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_USER_START_STOP);
				tempArchiveSettings.canUserStopArchive = CHECKBOX_GetState(hItem);

				if (bkArchiveSettings.ArchivizationFrequency1 != tempArchiveSettings.ArchivizationFrequency1 ||
				bkArchiveSettings.ArchivizationFrequency2 != tempArchiveSettings.ArchivizationFrequency2 ||
				bkArchiveSettings.TotalizerArchivizationFrequency != tempArchiveSettings.TotalizerArchivizationFrequency ||
				bkArchiveSettings.ArchiveMaxSize != tempArchiveSettings.ArchiveMaxSize)
				{
					NewArchive = 1;
					NewSettings = 1;
					CopyArchiveSettings(&bkArchiveSettings, &tempArchiveSettings);
				}
				if(bkArchiveSettings.canUserStopArchive != tempArchiveSettings.canUserStopArchive)
				{
					NewSettings = 1;
					CopyArchiveSettings(&bkArchiveSettings, &tempArchiveSettings);
				}

				WM_DeleteWindow(pMsg->hWin);
				break;
			}
			break;
		case ID_BUTTON_CANCEL:
			switch (NCode)
			{
			case WM_NOTIFICATION_RELEASED:
				BUZZER_Beep();
				WM_DeleteWindow(pMsg->hWin);
				break;
			}
			break;
		case ID_DROPDOWN_ARCHIVE_FREQUENCY_1:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				BUZZER_Beep();
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				BUZZER_Beep();
				tempArchiveSettings.ArchivizationFrequency1 = DROPDOWN_GetSel(pMsg->hWinSrc);
				break;
			}
			break;
		case ID_DROPDOWN_ARCHIVE_FREQUENCY_2:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				BUZZER_Beep();
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				BUZZER_Beep();
				tempArchiveSettings.ArchivizationFrequency2 = DROPDOWN_GetSel(pMsg->hWinSrc);
				break;
			}
			break;
		case ID_DROPDOWN_TOT_ARCHIVE_FREQUENCY:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				BUZZER_Beep();
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				BUZZER_Beep();
				tempArchiveSettings.TotalizerArchivizationFrequency = DROPDOWN_GetSel(pMsg->hWinSrc);
				break;
			}
			break;
		case ID_DROPDOWN_ARCHIVE_SIZE:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				BUZZER_Beep();
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				BUZZER_Beep();
				tempArchiveSettings.ArchiveMaxSize = DROPDOWN_GetSel(pMsg->hWinSrc);
				break;
			}
			break;
		case ID_MULTIPAGE_ARCHIVE_DATA:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				BUZZER_Beep();
				break;
			}
			break;
		case ID_CHECKBOX_USER_START_STOP:
			switch (NCode)
			{
			case WM_NOTIFICATION_RELEASED:
				BUZZER_Beep();
				tempArchiveSettings.canUserStopArchive = DROPDOWN_GetSel(pMsg->hWinSrc);
				break;
			}
			break;
		}
		break;
	case WM_POST_PAINT:
		DRAW_Text("I:", 355, 57, GUI_BLUE, GUI_TRANSPARENT, &GUI_FontLato30);
		DRAW_Text("II:", 575, 57, GUI_BLUE, GUI_TRANSPARENT, &GUI_FontLato30);
		break;
	case WM_USER_LOGIN:
		if (PASSWORDS_GetCurrentLevel() < USER_LEVEL)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
			WM_HideWindow(hItem);
		}

		break;
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

WM_HWIN CreateSetArchive(WM_HWIN hParent)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(_aSetArchiveDialogCreate, GUI_COUNTOF(_aSetArchiveDialogCreate), _cbSetArchiveDialog, hParent, 0, 0);
	USERMESSAGE_ChangeWinTitle(GUI_LANG_GetText(4));
	return hWin;
}
